# Generated by Django 2.1.4 on 2018-12-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_recorder.Category')),
            ],
            options={
                'ordering': ('parent', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='event_recorder.Category')),
            ],
            options={
                'ordering': ('-end_time', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('approx_DOB', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'LGBTQ')], max_length=5, null=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Relationship Category')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoyment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Enjoyment Rating')),
                ('productivity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Productivity Rating')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_recorder.Event')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(to='event_recorder.Relation'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(null=True, to='event_recorder.Person'),
        ),
    ]
