# Generated by Django 2.1.4 on 2018-12-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='event_recorder.Person'),
        ),
    ]
