# Generated by Django 2.1.4 on 2018-12-21 04:45

from django.db import migrations, models
import event_recorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0004_auto_20181220_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='event_recorder.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[(event_recorder.models.GenderChoices('Male'), 'Male'), (event_recorder.models.GenderChoices('Female'), 'Female'), (event_recorder.models.GenderChoices('LGBTQ'), 'LGBTQ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(null=True, to='event_recorder.Relation'),
        ),
    ]
