# Generated by Django 2.1.4 on 2018-12-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0005_auto_20181220_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(to='event_recorder.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(to='event_recorder.Relation'),
        ),
    ]
