# Generated by Django 2.1.4 on 2018-12-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0006_auto_20181220_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'LGBTQ')], max_length=1, null=True),
        ),
    ]
