# Generated by Django 2.1.4 on 2018-12-23 20:18

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0009_auto_20181221_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('parent'), nulls_first=True), 'name']},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ('name',)},
        ),
    ]
