# Generated by Django 2.1.4 on 2018-12-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0010_auto_20181223_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='Rating',
        ),
    ]
