# Generated by Django 2.1.4 on 2018-12-24 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0012_auto_20181223_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 2, 21, 7, 343947, tzinfo=utc)),
        ),
    ]
