# Generated by Django 2.1.4 on 2018-12-24 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0013_auto_20181223_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 2, 34, 40, 649707, tzinfo=utc)),
        ),
    ]
