# Generated by Django 2.1.4 on 2018-12-25 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_recorder', '0014_auto_20181223_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 32, 28, 187345, tzinfo=utc)),
        ),
    ]
